---

- hosts: all
  become: true
  tasks:

  - name: Install apache and php packages
    yum:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
  
    when: ansible_distribution in ["Ubuntu","CentOs"] 
      #when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "8.2" 
